---
title: Green goals
hero_image: images/banner.png
description: Program an animation and learn about the United Nations five environment-focused
  Sustainable Development Goals
version: 4
listed: true
copyedit: true
last_tested: '2020-08-19'
steps:
- title: Introduction
- title: Walk through the goals
- title: Climate Action
  completion:
  - engaged
- title: Affordable and Clean Energy
- title: Responsible Consumption and Production
- title: Life Below Water
- title: Life on Land
  completion:
  - internal
- title: Share your project
  completion:
  - external