title: green-goals
hero_image: images/banner.png
description: green-goals description
version: 4
listed: false
copyedit: false
last_tested: "2020-08-19"
steps:
  - title: Introduction
  - title: Walk through the goals
  - title: Climate action
  - title: Affordable and clean energy
  - title: Responsible consumption and development
  - title: Life below water
  - title: Life on land
  - title: What next?
