title: Green goals
hero_image: images/banner.png
description: green-goals description
version: 4
listed: false
copyedit: false
last_tested: "2020-08-19"
steps:
  - title: Introduction
  - title: Walk through the goals
  - title: Climate action
  - title: Affordable and clean energy
  - title: Responsible consumption and production
  - title: Life Below Water
  - title: Life on Land
  - title: "Challenge: get creative"
  - title: Share your project
  - title: What next?
